### ISSUE TITLE
Introduce expclit step ordering and dependency

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-ci#9]
In the current implementation all steps have to be explicitly executed. There are no concept of dependencies and/or order.

Considering the implicit order of all `step(n)` is the following:

* `before_install` -> `step(1)`
* `install` -> `step(2)`
* `before_build` -> `step(3)`
* `build` -> `step(4)`
* `test` -> `step(5)`
* `after_test` -> `step(6)`

The proposal is to ensure that executing any `step(n)` using `ci step(n)` ensures that `step(n-1)` has been executed before.

Doing so will allow to update configuration like this one:

```yml
dependencies:
  override:
    - ci before_install
    - ci install

test:
  override:
    - ci before_build
    - ci build
    - ci test

deployment:
  master:
    branch: master
    commands:
      - ci after_test
```

into 

```yml
dependencies:
  override:
    - ci install

test:
  override:
    - ci test

deployment:
  master:
    branch: master
    commands:
      - ci after_test
```
